### ISSUE TITLE
Is this project now dead / unmaintained?

### ISSUE THREAD

**Issue by smutch** [ivanov/vim-ipython#153]
I _very_ thankful for this plugin and the fantastic work which has gone into creating it.  I realise that nothing is owed to myself or others who are using this, but it would be great to hear what the future plans are for this plugin and if it is being / will be maintained?  There are currently a lot of open issues and pull requests.

@wilywampa has an excellent fork which appears to have been maintained and updated regularly to keep pace with IPython.  Unfortunately, Github appears to have some restrictions on creating pull requests for forks-of-forks (or at-least I am having troubles achieving this), so it is not possible to submit a pull request to this maintained repo...

**Comment by ocehugo** [comment]
I believe that if someone is keen to take the the lead (@wilywampa looks like the guy :P) and other people that make changes get together and organize the pull requests the thing will get better. I did some issues and pull requests not required since I didn't check pther pulls, etc. From the fork graph I believe that @wilywampa and @jjhelmus are the guys to talk about it, since most of other forks were doing exactly the same (support for python3 or jupyter, etc).

**Comment by khughitt** [comment]
@ivanov Perhaps you could add @wilywampa as a maintainer for the repo? This way he could help to merge some of the PRs.

This seems to have worked quite well recently for another  NerdCommenter (e.g. see discussion here: https://github.com/scrooloose/nerdcommenter/pull/218)

**Comment by wilywampa** [comment]
The main reason I haven't replied yet is I'm just trying to figure out the best way to get all the functionality that I've put together for myself out to everyone else. Some features I've come to depend on which are built on features that I will maintain in my fork:
1. Metadata for completion showing live values of variables, docstrings, and more allowing quick inspection of variables just by typing
2. A monitor for the console shell that shows the inputs and outputs in the shell itself instead of in a Vim window
3. A [unite](https://github.com/Shougo/unite.vim) IPython history source to allow searching, copying, executing, etc. IPython history items
4. A scratch buffer that behaves a lot like an IPython notebook but with the ability to act on text objects/motions instead of just cells (plus full Vim editing support, which is what we're all here for, right?)

I made a little demo to show off some of this stuff:

![ipydemo3](https://cloud.githubusercontent.com/assets/4472522/16790097/d548393e-4867-11e6-8da6-406ee086537f.gif)

None of this is really documented and most of it is external to the Vim plugin; some even requires modification to IPython itself. If there's any interest I can maybe put some effort into making things usable for other people.

**Comment by ocehugo** [comment]
Hi, i'm interested particularly in 1. and 2. (mostly in the console monitor). I disable the ipython buffer since it's too slow and all the time it's get in the way ( you can't check if the code was run though, sometimes a little bit problematic but easily handled by syntastic but also required to run the code checker or save the file). The demonstration video is nice, but too quick (or I need more coffee).

I also ask myself if 1 is build to work together with YouCompleteMe.

I do not write vimscripts but i can try to use/debug a little bit. Let me know when you put some help/readme with your changes,installing, like mappings and what each option do what,  so I can give a try

**Comment by smutch** [comment]
@wilywampa - that looks amazing!  Thanks for sharing your progress!

I too am having a little trouble following the demo video, but the features you've described sound great.  If you were able to find the time to develop your branch into a more friendly version for others to use then I too would be happy and willing to help out with testing etc...

**Comment by wilywampa** [comment]
A version of my fork with metadata/monitor documented is available now: https://github.com/wilywampa/vim-ipython/commit/ed4c2dc302718712db0df2e6634068c284a6df55

**Comment by smutch** [comment]
Awesome!  Thanks for passing this on.  I'll try it out and let you know how I get on.

**Comment by ocehugo** [comment]
@wilywampa, could you open the issues tab on your fork? I had some problems, like the command to run several lines do not work and I can't find some other functions names (Like runCell for example).

**Comment by wilywampa** [comment]
@ocehugo I opened up issues and added an implementation for `<Plug>(IPython-RunCell)`. It actually runs a paragraph but it's built on a `<Plug>(IPython-RunTextObj)` map that could be combined with, for example, https://github.com/kana/vim-textobj-user to define a cell however you like.

**Comment by wmvanvliet** [comment]
FYI: I've been working from the Jupyter QtConsole end to support better integration with text editors like Vim: https://github.com/jupyter/qtconsole/pull/196

**Comment by ivanov** [comment]
Thanks @smutch for the kind words, and all of you for playing with vim-ipython - I'm glad it's been useful, and sorry to have been rather absent in the past few years.

Software does not die. It is just a collections of bits. The bits are there for you to use and bend and meld to your own needs. I am glad that some of you have been able to make progress with your own forks. It has always been my intent to continue development of vim-ipython, but other things got in the way of that. I hope you all understand and I will try to do better. I am closing this issue to signal that this project is not dead, feel free to provide any other updates here or by opening a new issue.

Happy hacking! :bowtie:
